/**
 * Skills "extra" auto-generadas para MAIA, inspiradas en NotebookLM, n8n,
 * Twin AI, Open Interpreter, Self-Operating-Computer y AutoGPT.
 * Cada entrada se materializa como `~/.openclaw/workspace/skills/<name>/SKILL.md`.
 */

export interface ExtraSkill {
  name: string;
  category: string;
  description: string;
  triggers: string[];
  needs: string[];
  inspiration: string;
}

export const EXTRA_SKILLS: ExtraSkill[] = [
  {
    name: "notebook-source-organizer",
    category: "knowledge",
    description: "Ingesta multi-fuente (URL, PDF, YouTube, audio) en notebooks con re-indexación incremental.",
    triggers: ["abrir notebook", "añadir fuente", "indexa esto"],
    needs: ["rag-pipeline", "vision-documentparser", "realtimedata-websearch"],
    inspiration: "NotebookLM",
  },
  {
    name: "notebook-audio-overview",
    category: "knowledge",
    description: "Genera un audio-resumen tipo podcast desde las fuentes de un notebook.",
    triggers: ["audio overview", "resumen en podcast"],
    needs: ["context-summarizer", "creativewriting-author"],
    inspiration: "NotebookLM",
  },
  {
    name: "daily-briefing",
    category: "personal",
    description: "Resumen matutino: calendario, email, tareas, noticias, clima.",
    triggers: ["briefing", "buenos dias", "qué toca hoy"],
    needs: ["realtimedata-apiintegrator", "context-summarizer"],
    inspiration: "Twin / Reflect / Notion AI",
  },
  {
    name: "smart-clipboard",
    category: "personal",
    description: "Captura, clasifica y enriquece todo lo que copias al portapapeles.",
    triggers: ["copiado nuevo", "clipboard"],
    needs: ["structuredoutput-json"],
    inspiration: "Raycast / Paste / Maccy",
  },
  {
    name: "screen-recorder-summarizer",
    category: "computeruse",
    description: "Graba pantalla y produce transcripción + capítulos + acciones detectadas.",
    triggers: ["graba pantalla", "qué hice ahora"],
    needs: ["vision-imageanalyzer", "computeruse-terminalagent"],
    inspiration: "rewind.ai",
  },
  {
    name: "voice-memo-transcriber",
    category: "personal",
    description: "Transcribe notas de voz y extrae tareas, fechas y recordatorios.",
    triggers: ["nota de voz", "transcribe"],
    needs: ["context-summarizer", "structuredoutput-json"],
    inspiration: "AudioPen / Whisper",
  },
  {
    name: "workflow-canvas-builder",
    category: "automation",
    description: "Genera flujos visuales tipo n8n a partir de lenguaje natural.",
    triggers: ["crea flujo", "automatiza esto"],
    needs: ["reasoning-planner", "structuredoutput-json"],
    inspiration: "n8n + Twin builder",
  },
  {
    name: "trigger-scheduler",
    category: "automation",
    description: "Cron, webhook, evento, cambio-de-archivo unificados como disparadores.",
    triggers: ["cada", "cuando llegue", "al cambiar"],
    needs: ["automation"],
    inspiration: "n8n triggers",
  },
  {
    name: "model-router-arbitrage",
    category: "inference",
    description: "Selecciona el modelo más eficiente (calidad / latencia / coste) por subtarea.",
    triggers: ["pensar mas", "rapido", "barato"],
    needs: ["inference-optimizer"],
    inspiration: "Twin AI",
  },
  {
    name: "web-schema-extractor",
    category: "research",
    description: "Scraping estructurado declarativo: pasas un esquema JSON, devuelve datos.",
    triggers: ["extrae de", "schema scraping"],
    needs: ["realtimedata-websearch", "structuredoutput-json"],
    inspiration: "Twin AI / Bardeen",
  },
  {
    name: "browser-form-filler",
    category: "computeruse",
    description: "Rellena y envía formularios web complejos con validación y captcha-aware.",
    triggers: ["rellena este form", "envía solicitud"],
    needs: ["computeruse-browseragent"],
    inspiration: "Browser-Use / Skyvern",
  },
  {
    name: "desktop-ui-tester",
    category: "computeruse",
    description: "Pruebas E2E de apps de escritorio con visión + clicks reproducibles.",
    triggers: ["test ui", "qa app"],
    needs: ["pc-control", "vision-imageanalyzer"],
    inspiration: "OmniParser / Anthropic Computer Use",
  },
  {
    name: "file-watcher-automator",
    category: "automation",
    description: "Acciones automáticas al detectar cambios en carpetas locales o cloud.",
    triggers: ["cuando aparezca un archivo", "watch folder"],
    needs: ["automation"],
    inspiration: "Hazel / n8n FS trigger",
  },
  {
    name: "email-triage",
    category: "personal",
    description: "Clasifica, etiqueta, responde y archiva email entrante.",
    triggers: ["revisa email", "limpia bandeja"],
    needs: ["realtimedata-apiintegrator", "creativewriting-editor"],
    inspiration: "Superhuman / Shortwave",
  },
  {
    name: "meeting-notetaker",
    category: "personal",
    description: "Transcribe reuniones, extrae decisiones, asigna action items.",
    triggers: ["nota de reunión", "minuta"],
    needs: ["context-summarizer", "structuredoutput-table"],
    inspiration: "Granola / Otter",
  },
  {
    name: "research-deep-dive",
    category: "research",
    description: "Modo investigación profunda multi-fuente con citas y fact-check.",
    triggers: ["investigación profunda", "deep research"],
    needs: ["rag-pipeline", "factcheck-claimverifier", "realtimedata-websearch"],
    inspiration: "Perplexity Pages / NotebookLM",
  },
  {
    name: "pdf-source-chatter",
    category: "knowledge",
    description: "Conversación RAG con PDFs largos manteniendo citas exactas a página.",
    triggers: ["preguntale al pdf", "chat con documento"],
    needs: ["rag-pipeline", "vision-documentparser"],
    inspiration: "ChatPDF / NotebookLM",
  },
  {
    name: "youtube-knowledge-extractor",
    category: "knowledge",
    description: "Transcribe + indexa + Q&A sobre videos de YouTube.",
    triggers: ["resume video", "youtube qa"],
    needs: ["rag-pipeline"],
    inspiration: "NotebookLM / Eightify",
  },
  {
    name: "personal-knowledge-graph",
    category: "knowledge",
    description: "Construye un grafo de conocimiento personal a partir de notas y fuentes.",
    triggers: ["mapa mental", "knowledge graph"],
    needs: ["rag-pipeline", "structuredoutput-json"],
    inspiration: "Mem / Reflect / Logseq",
  },
  {
    name: "habit-tracker-coach",
    category: "personal",
    description: "Registra hábitos y ofrece coaching diario adaptativo.",
    triggers: ["hábitos", "coach"],
    needs: ["context-memorymanager"],
    inspiration: "Streaks / Habitica",
  },
  {
    name: "expense-categorizer",
    category: "personal",
    description: "OCR de recibos + categorización automática + reportes mensuales.",
    triggers: ["gastos", "facturita"],
    needs: ["vision-ocr", "domain-financial", "structuredoutput-table"],
    inspiration: "Cleo / Splitwise",
  },
  {
    name: "news-digest-curator",
    category: "research",
    description: "Curaduría diaria personalizada con resúmenes y verificación de hechos.",
    triggers: ["noticias", "digest"],
    needs: ["realtimedata-websearch", "factcheck-claimverifier"],
    inspiration: "Artifact (RIP) / Smartnews",
  },
  {
    name: "code-screenshot-explainer",
    category: "code",
    description: "Explica código a partir de capturas de pantalla con OCR + análisis.",
    triggers: ["explica esta captura", "qué hace este código"],
    needs: ["vision-ocr", "codeexecution-validator"],
    inspiration: "GitHub Copilot Vision",
  },
  {
    name: "cross-app-paste-translator",
    category: "personal",
    description: "Al pegar entre apps, traduce/transforma según el destino (ej. Markdown→Notion).",
    triggers: ["pega traducido", "transforma al pegar"],
    needs: ["spanish-translator", "structuredoutput-code"],
    inspiration: "Raycast paste hooks",
  },
  {
    name: "agent-self-improver",
    category: "meta",
    description: "Audita y refactoriza prompts/skills propios de MAIA según telemetría.",
    triggers: ["mejora skills", "self-improve"],
    needs: ["factcheck-selfcorrector", "rag-evaluator"],
    inspiration: "DSPy / Promptbreeder",
  },
];
