/**
 * Skills "extra" auto-generadas para MAIA, inspiradas en NotebookLM, n8n,
 * Twin AI, Open Interpreter, Self-Operating-Computer y AutoGPT.
 * Cada entrada se materializa como `~/.openclaw/workspace/skills/<name>/SKILL.md`.
 */

export interface ExtraSkill {
  name: string;
  category: string;
  description: string;
  triggers: string[];
  needs: string[];
  inspiration: string;
}

export const EXTRA_SKILLS: ExtraSkill[] = [
  {
    name: "notebook-source-organizer",
    category: "knowledge",
    description: "Ingesta multi-fuente (URL, PDF, YouTube, audio) en notebooks con re-indexación incremental.",
    triggers: ["abrir notebook", "añadir fuente", "indexa esto"],
    needs: ["rag-pipeline", "vision-documentparser", "realtimedata-websearch"],
    inspiration: "NotebookLM",
  },
  {
    name: "notebook-audio-overview",
    category: "knowledge",
    description: "Genera un audio-resumen tipo podcast desde las fuentes de un notebook.",
    triggers: ["audio overview", "resumen en podcast"],
    needs: ["context-summarizer", "creativewriting-author"],
    inspiration: "NotebookLM",
  },
  {
    name: "daily-briefing",
    category: "personal",
    description: "Resumen matutino: calendario, email, tareas, noticias, clima.",
    triggers: ["briefing", "buenos dias", "qué toca hoy"],
    needs: ["realtimedata-apiintegrator", "context-summarizer"],
    inspiration: "Twin / Reflect / Notion AI",
  },
  {
    name: "smart-clipboard",
    category: "personal",
    description: "Captura, clasifica y enriquece todo lo que copias al portapapeles.",
    triggers: ["copiado nuevo", "clipboard"],
    needs: ["structuredoutput-json"],
    inspiration: "Raycast / Paste / Maccy",
  },
  {
    name: "screen-recorder-summarizer",
    category: "computeruse",
    description: "Graba pantalla y produce transcripción + capítulos + acciones detectadas.",
    triggers: ["graba pantalla", "qué hice ahora"],
    needs: ["vision-imageanalyzer", "computeruse-terminalagent"],
    inspiration: "rewind.ai",
  },
  {
    name: "voice-memo-transcriber",
    category: "personal",
    description: "Transcribe notas de voz y extrae tareas, fechas y recordatorios.",
    triggers: ["nota de voz", "transcribe"],
    needs: ["context-summarizer", "structuredoutput-json"],
    inspiration: "AudioPen / Whisper",
  },
  {
    name: "workflow-canvas-builder",
    category: "automation",
    description: "Genera flujos visuales tipo n8n a partir de lenguaje natural.",
    triggers: ["crea flujo", "automatiza esto"],
    needs: ["reasoning-planner", "structuredoutput-json"],
    inspiration: "n8n + Twin builder",
  },
  {
    name: "trigger-scheduler",
    category: "automation",
    description: "Cron, webhook, evento, cambio-de-archivo unificados como disparadores.",
    triggers: ["cada", "cuando llegue", "al cambiar"],
    needs: ["automation"],
    inspiration: "n8n triggers",
  },
  {
    name: "model-router-arbitrage",
    category: "inference",
    description: "Selecciona el modelo más eficiente (calidad / latencia / coste) por subtarea.",
    triggers: ["pensar mas", "rapido", "barato"],
    needs: ["inference-optimizer"],
    inspiration: "Twin AI",
  },
  {
    name: "web-schema-extractor",
    category: "research",
    description: "Scraping estructurado declarativo: pasas un esquema JSON, devuelve datos.",
    triggers: ["extrae de", "schema scraping"],
    needs: ["realtimedata-websearch", "structuredoutput-json"],
    inspiration: "Twin AI / Bardeen",
  },
  {
    name: "browser-form-filler",
    category: "computeruse",
    description: "Rellena y envía formularios web complejos con validación y captcha-aware.",
    triggers: ["rellena este form", "envía solicitud"],
    needs: ["computeruse-browseragent"],
    inspiration: "Browser-Use / Skyvern",
  },
  {
    name: "desktop-ui-tester",
    category: "computeruse",
    description: "Pruebas E2E de apps de escritorio con visión + clicks reproducibles.",
    triggers: ["test ui", "qa app"],
    needs: ["pc-control", "vision-imageanalyzer"],
    inspiration: "OmniParser / Anthropic Computer Use",
  },
  {
    name: "file-watcher-automator",
    category: "automation",
    description: "Acciones automáticas al detectar cambios en carpetas locales o cloud.",
    triggers: ["cuando aparezca un archivo", "watch folder"],
    needs: ["automation"],
    inspiration: "Hazel / n8n FS trigger",
  },
  {
    name: "email-triage",
    category: "personal",
    description: "Clasifica, etiqueta, responde y archiva email entrante.",
    triggers: ["revisa email", "limpia bandeja"],
    needs: ["realtimedata-apiintegrator", "creativewriting-editor"],
    inspiration: "Superhuman / Shortwave",
  },
  {
    name: "meeting-notetaker",
    category: "personal",
    description: "Transcribe reuniones, extrae decisiones, asigna action items.",
    triggers: ["nota de reunión", "minuta"],
    needs: ["context-summarizer", "structuredoutput-table"],
    inspiration: "Granola / Otter",
  },
  {
    name: "research-deep-dive",
    category: "research",
    description: "Modo investigación profunda multi-fuente con citas y fact-check.",
    triggers: ["investigación profunda", "deep research"],
    needs: ["rag-pipeline", "factcheck-claimverifier", "realtimedata-websearch"],
    inspiration: "Perplexity Pages / NotebookLM",
  },
  {
    name: "pdf-source-chatter",
    category: "knowledge",
    description: "Conversación RAG con PDFs largos manteniendo citas exactas a página.",
    triggers: ["preguntale al pdf", "chat con documento"],
    needs: ["rag-pipeline", "vision-documentparser"],
    inspiration: "ChatPDF / NotebookLM",
  },
  {
    name: "youtube-knowledge-extractor",
    category: "knowledge",
    description: "Transcribe + indexa + Q&A sobre videos de YouTube.",
    triggers: ["resume video", "youtube qa"],
    needs: ["rag-pipeline"],
    inspiration: "NotebookLM / Eightify",
  },
  {
    name: "personal-knowledge-graph",
    category: "knowledge",
    description: "Construye un grafo de conocimiento personal a partir de notas y fuentes.",
    triggers: ["mapa mental", "knowledge graph"],
    needs: ["rag-pipeline", "structuredoutput-json"],
    inspiration: "Mem / Reflect / Logseq",
  },
  {
    name: "habit-tracker-coach",
    category: "personal",
    description: "Registra hábitos y ofrece coaching diario adaptativo.",
    triggers: ["hábitos", "coach"],
    needs: ["context-memorymanager"],
    inspiration: "Streaks / Habitica",
  },
  {
    name: "expense-categorizer",
    category: "personal",
    description: "OCR de recibos + categorización automática + reportes mensuales.",
    triggers: ["gastos", "facturita"],
    needs: ["vision-ocr", "domain-financial", "structuredoutput-table"],
    inspiration: "Cleo / Splitwise",
  },
  {
    name: "news-digest-curator",
    category: "research",
    description: "Curaduría diaria personalizada con resúmenes y verificación de hechos.",
    triggers: ["noticias", "digest"],
    needs: ["realtimedata-websearch", "factcheck-claimverifier"],
    inspiration: "Artifact (RIP) / Smartnews",
  },
  {
    name: "code-screenshot-explainer",
    category: "code",
    description: "Explica código a partir de capturas de pantalla con OCR + análisis.",
    triggers: ["explica esta captura", "qué hace este código"],
    needs: ["vision-ocr", "codeexecution-validator"],
    inspiration: "GitHub Copilot Vision",
  },
  {
    name: "cross-app-paste-translator",
    category: "personal",
    description: "Al pegar entre apps, traduce/transforma según el destino (ej. Markdown→Notion).",
    triggers: ["pega traducido", "transforma al pegar"],
    needs: ["spanish-translator", "structuredoutput-code"],
    inspiration: "Raycast paste hooks",
  },
  {
    name: "agent-self-improver",
    category: "meta",
    description: "Audita y refactoriza prompts/skills propios de MAIA según telemetría.",
    triggers: ["mejora skills", "self-improve"],
    needs: ["factcheck-selfcorrector", "rag-evaluator"],
    inspiration: "DSPy / Promptbreeder",
  },

  /* ───── ronda 2: inspiración Cluely, Cap, Wispr, Granola, Letta, Moondream, etc. ───── */
  { name: "whisper-coach",                category: "personal",   description: "Overlay invisible que escucha llamadas y susurra respuestas/datos contextuales.", triggers: ["coach silencioso", "ayuda en llamada"], needs: ["realtimedata-websearch", "context-summarizer"],         inspiration: "Cluely" },
  { name: "tone-adapter",                 category: "personal",   description: "Ajusta el registro del texto al destinatario y app de destino.",                triggers: ["formal", "tono casual"],                  needs: ["creativewriting-editor"],                                  inspiration: "Wispr Flow" },
  { name: "chapter-marker",               category: "computeruse",description: "Divide grabaciones largas en capítulos navegables por cambio de tema.",         triggers: ["capitulos", "marca segmentos"],           needs: ["context-summarizer"],                                      inspiration: "Cap" },
  { name: "screenshot-archaeologist",     category: "knowledge",  description: "Indexa toda la carpeta de capturas y permite buscar por contenido visual+OCR.", triggers: ["busca screenshot", "donde vi"],          needs: ["vision-ocr", "rag-pipeline"],                              inspiration: "Macroscope" },
  { name: "hybrid-notes-augmenter",       category: "personal",   description: "Enriquece notas manuales con transcript completo del meeting.",                  triggers: ["mejora mis notas"],                       needs: ["context-summarizer"],                                      inspiration: "Granola" },
  { name: "action-item-router",           category: "personal",   description: "Extrae action items y los enruta a Linear/Asana/Notion según owner.",            triggers: ["tareas del meeting"],                     needs: ["structuredoutput-json", "realtimedata-apiintegrator"],     inspiration: "Fellow / Otter" },
  { name: "ambient-life-logger",          category: "personal",   description: "Grabación ambiental por bloques con auto-borrado tras N días salvo marcado.",   triggers: ["loggea mi dia"],                          needs: ["context-memorymanager"],                                   inspiration: "Recall.ai / Plaud" },
  { name: "memory-portability-bridge",    category: "meta",       description: "Exporta/importa memoria del agente entre Claude/GPT/Gemini sin perder contexto.",triggers: ["mover memoria"],                          needs: ["context-memorymanager"],                                   inspiration: "Letta" },
  { name: "natural-shell",                category: "computeruse",description: "Traduce instrucciones en español a comandos shell con preview/dry-run.",        triggers: ["en bash haz", "comando para"],            needs: ["computeruse-terminalagent", "codeexecution-validator"],    inspiration: "Open Interpreter" },
  { name: "local-vision-glance",          category: "vision",     description: "Análisis visual continuo de pantalla 100% local (Moondream-style).",            triggers: ["mira mi pantalla"],                       needs: ["vision-imageanalyzer"],                                    inspiration: "Moondream" },
  { name: "role-cast-builder",            category: "automation", description: "Genera dinámicamente un crew de sub-agentes con roles según la tarea.",          triggers: ["arma equipo", "crew"],                    needs: ["orchestrator-multiagent"],                                 inspiration: "CrewAI" },
  { name: "background-browse-agent",      category: "research",   description: "Abre tabs ocultas y completa research multi-paso mientras trabajas.",            triggers: ["investiga en background"],                needs: ["computeruse-browseragent", "research"],                    inspiration: "Comet / Arc" },
  { name: "app-action-recorder",          category: "automation", description: "Graba secuencias de UI y las replica como macros aprendidas.",                  triggers: ["graba esto", "macro"],                    needs: ["pc-control"],                                              inspiration: "Rabbit r1 / LAM" },
  { name: "point-and-translate",          category: "vision",     description: "Apuntar cámara/screenshot a algo y obtener traducción con contexto cultural.",  triggers: ["traduce esto", "que dice eso"],           needs: ["vision-ocr", "spanish-translator"],                        inspiration: "Humane Pin" },
  { name: "mood-companion",               category: "personal",   description: "Check-ins empáticos basados en tono detectado en voz y escritura.",              triggers: ["como estoy"],                             needs: ["context-memorymanager"],                                   inspiration: "Friend / Bee" },
  { name: "auto-backlink-weaver",         category: "knowledge",  description: "Crea links bidireccionales entre notas en background.",                          triggers: ["conecta notas"],                          needs: ["rag-pipeline"],                                            inspiration: "Reflect / Mem" },
  { name: "procedure-compiler",           category: "automation", description: "Convierte SOPs en lenguaje natural a flowcharts ejecutables auditables.",       triggers: ["proceso a flujo"],                        needs: ["structuredoutput-json"],                                   inspiration: "Decagon" },
  { name: "persona-employee-spawner",     category: "automation", description: "Instancia empleados virtuales con calendario, inbox y métricas propias.",       triggers: ["nuevo empleado virtual"],                 needs: ["orchestrator-multiagent"],                                 inspiration: "Lindy" },
  { name: "integration-discoverer",       category: "automation", description: "Escanea apps instaladas y sugiere automations rentables.",                       triggers: ["que automatizo"],                         needs: ["pc-control", "automation"],                                inspiration: "Bardeen / Pipedream" },
  { name: "visual-selector-healer",       category: "computeruse",description: "Repara selectores web rotos usando visión del DOM renderizado.",                triggers: ["fix scraper"],                            needs: ["vision-imageanalyzer", "computeruse-browseragent"],        inspiration: "Skyvern" },
  { name: "context-leak-guard",           category: "safety",     description: "Bloquea info confidencial antes de pegarla en LLMs públicos.",                   triggers: ["antes de pegar"],                         needs: ["safety-contentfilter"],                                    inspiration: "Daxa / private LLM proxies" },
  { name: "voice-shortcut-vault",         category: "personal",   description: "Dispara macros largas con frases gatillo personales.",                           triggers: ["modo focus", "modo viaje"],               needs: ["automation"],                                              inspiration: "Apple Shortcuts + voz" },
  { name: "multi-tab-snapshot",           category: "research",   description: "Guarda y restaura sesiones completas de browser con anotaciones.",                triggers: ["guarda mis tabs"],                        needs: ["computeruse-browseragent"],                                inspiration: "Arc Spaces" },
  { name: "silent-meeting-summarizer",    category: "personal",   description: "Resume meetings sin que aparezca un bot en la llamada.",                          triggers: ["resume sin bot"],                         needs: ["context-summarizer"],                                      inspiration: "Granola" },
  { name: "proactive-followup-drafter",   category: "personal",   description: "Borrador de email post-meeting listo para enviar.",                              triggers: ["follow up"],                              needs: ["creativewriting-author"],                                  inspiration: "Read.ai" },
  { name: "diff-narrator",                category: "code",       description: "Explica diffs de Git en lenguaje natural para reviewers.",                       triggers: ["explica este diff", "review"],            needs: ["codeexecution-validator"],                                 inspiration: "GitHub Copilot review" },
  { name: "local-rag-vault",              category: "knowledge",  description: "RAG sobre carpeta personal con embeddings locales y cifrado en reposo.",         triggers: ["busca en mi carpeta"],                    needs: ["rag-pipeline"],                                            inspiration: "Reor / GPT4All" },
  { name: "desktop-window-arranger",      category: "computeruse",description: "Organiza ventanas según el modo detectado (focus/calls/coding).",                triggers: ["modo focus", "modo coding"],              needs: ["pc-control"],                                              inspiration: "Rectangle / Yabai + AI" },
  { name: "clipboard-history-search",     category: "personal",   description: "Búsqueda semántica en histórico de portapapeles.",                                triggers: ["busca en portapapeles"],                  needs: ["rag-pipeline"],                                            inspiration: "Maccy / Paste" },
  { name: "calendar-defender",            category: "personal",   description: "Bloquea focus-time y rechaza meetings de baja prioridad con un mensaje educado.",triggers: ["protege mi tiempo"],                      needs: ["realtimedata-apiintegrator", "creativewriting-editor"],    inspiration: "Reclaim / Motion" },
  { name: "energy-aware-scheduler",       category: "personal",   description: "Agenda tareas según ritmo circadiano y energía detectada.",                       triggers: ["cuando hago X"],                          needs: ["context-memorymanager"],                                   inspiration: "Motion / Reclaim" },
  { name: "ambient-fact-surfacer",        category: "knowledge",  description: "Surfacea datos relevantes mientras lees/escribes sin que se los pidas.",         triggers: ["", "(ambient)"],                          needs: ["rag-pipeline"],                                            inspiration: "Mem.ai inline" },
  { name: "agent-cost-meter",             category: "meta",       description: "Monitor de gasto en tokens por skill con alertas.",                              triggers: ["cuanto gastamos"],                        needs: ["inference-optimizer"],                                     inspiration: "Helicone / Langfuse" },
  { name: "voice-clone-quickreply",       category: "personal",   description: "Responde voicemails con tu voz clonada localmente.",                              triggers: ["responde con mi voz"],                    needs: ["realtimedata-apiintegrator"],                              inspiration: "ElevenLabs" },
  { name: "screen-region-watcher",        category: "computeruse",description: "Dispara acciones cuando una región pixelada de la pantalla cambia.",            triggers: ["vigila este area"],                       needs: ["vision-imageanalyzer", "automation"],                      inspiration: "Hammerspoon" },
  { name: "pdf-form-autofiller",          category: "personal",   description: "Completa PDFs con datos de tu identidad/contexto.",                              triggers: ["rellena este pdf"],                       needs: ["vision-documentparser", "structuredoutput-json"],          inspiration: "DocSeal" },
  { name: "sop-from-recording",           category: "knowledge",  description: "Convierte una sesión grabada en SOP textual reutilizable.",                      triggers: ["genera sop"],                             needs: ["context-summarizer", "structuredoutput-table"],            inspiration: "Scribe" },
  { name: "local-action-model",           category: "automation", description: "Detecta acciones repetitivas y las ofrece como atajos aprendidos.",              triggers: ["(detección automática)"],                 needs: ["automation"],                                              inspiration: "LAM (Rabbit)" },
  { name: "multimodal-search-bar",        category: "knowledge",  description: "Barra única que busca en notas, tabs, files, audio y screenshots.",              triggers: ["busca", "ctrl+k"],                        needs: ["rag-pipeline", "vision-ocr"],                              inspiration: "Raycast + Spotlight" },
  { name: "agent-handoff-coordinator",    category: "meta",       description: "Pasa contexto entre agentes con resumen mínimo viable.",                          triggers: ["pasale a otro agente"],                   needs: ["orchestrator-multiagent", "context-summarizer"],           inspiration: "OpenAI Swarm" },
  { name: "permission-sandbox-broker",    category: "safety",     description: "Pide permisos solo cuando son necesarios y los expira automáticamente.",         triggers: ["permiso temporal"],                       needs: ["safety-refusalcalibrator"],                                inspiration: "Apple Privacy" },
];
