---
source_repo: https://github.com/aaronsb/google-workspace-mcp
source_file: src/version.ts
license: MIT
category: conectores-mcp/google-workspace
imported_at: 2026-04-19
---

// Auto-generated by `make version-stamp`. Do not edit manually.
export const VERSION = '2.6.1';
